spring.application.name=JobApply AI

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/jobapply
spring.datasource.username=jobapply
spring.datasource.password=jobapply

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true